{\rtf1\ansi\ansicpg1252\cocoartf2639
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\fs24 \cf0 apiVersion: apps/v1\
kind: Deployment\
metadata:\
  name: mysql\
  labels:\
    app: todonodejs\
    name: mysql\
spec:\
  replicas: 1\
  selector:\
    matchLabels:\
      app: todonodejs\
      name: mysql\
  template:\
    metadata:\
      labels:\
        app: todonodejs\
        name: mysql\
    spec:\
      containers:\
      - image: registry.access.redhat.com/rhscl/mysql-57-rhel7:5.7-47\
        name: mysql\
        env:\
        - name: MYSQL_ROOT_PASSWORD\
          value: r00tpa55\
        - name: MYSQL_USER\
          value: user1\
        - name: MYSQL_PASSWORD\
          value: mypa55\
        - name: MYSQL_DATABASE\
          value: items\
        ports:\
        - containerPort: 3306\
          name: mysql\
        volumeMounts:\
        - mountPath: "/var/lib/mysql"\
          name: db-volume\
      volumes:\
      - name: db-volume\
        emptyDir: \{\}\
      - name: db-init\
        emptyDir: \{\}\
---\
apiVersion: v1\
kind: Service\
metadata:\
  labels:\
    app: todonodejs\
    name: mysql\
  name: mysql\
spec:\
  ports:\
  - port: 3306\
  selector:\
    name: mysql\
}